name: rs_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pyqt
  - matplotlib
  - pandas
  - jupyterlab
  - scikit-learn
  - scipy
  - seaborn
  - numpy
  - ipywidgets
  - notebook
  - pyqtgraph
  - requests
  - psutil
  - typing-extensions
  - black        
  - flake8     
  - pyinstaller
  - pip
  - pip:
      - pyvisa
      - py-notifier
